name: Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive dist directory
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Run Jest tests
        run: npm test

      - name: Use API Key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Using API key: $API_KEY"
